### PR TITLE
feat: add ssg

### PR DESCRIPTION
**Pull request by YogiLiu**
CodeKitchen: https://codekitchen.community/t/topic/1230

### CODE REVIEW

**Comment by YogiLiu** [comment]
I'm confused. I don't know why the `pytest backend/tests/test_ssg.py` command is successful, but `pytest` is failed.

It seems like `pytest` execute the test function twice meanwhile, and lead to add a same Job ID to APScheduler.

@frostming Can you help me?

**Comment by frostming** [comment]
we have decided to use rq, there is no need for apscheduler. you can wait for #13 to be merged to avoid repeating work

**Comment by YogiLiu** [comment]
OK

**Comment by YogiLiu** [comment]
Refactor the code and use a new PR.

**Pull request closed without merging**
