### PR TITLE
refactor: restructure python files into backend folder

### PR DESCRIPTION
**Pull request by yuxiaoy1**

### CODE REVIEW

**Comment by frostming** [comment]
Why make this change, just for visual consistency? This adds some extra steps to switch directories. I think it's acceptable to have these files at the top level (I even want to put `package.json` at the top level).

**Comment by yuxiaoy1** [comment]
For decoupling frontend and backend, then both the directories can be a standalone repo and run individually.

**Comment by frostming** [comment]
> For decoupling frontend and backend, then both the directories can be a standalone repo and run individually.

I totally understand, but I think development experience wins here.

See https://github.com/wagtail/wagtail

It has really put so many stuff at the top level.

**Comment by yuxiaoy1** [comment]
The repo seems to be too messy here, anyway decoupling is always a good practice and more friendly to frontend/backend maintainers as you can work on your own directory.

**Comment by frostming** [comment]
> more friendly to frontend/backend maintainers as you can work on your own directory.

They don't always work separately, as a project at the early stage, we often need to look at backend and frontend side by side.

 @greyli need your final word on this.

**Comment by greyli** [comment]
Let's ensure a convenient development experience first.

This project is a combination of frontend and backend instead of a monorepo with separate (unrelated) sub-projects. So I prefer to keep all config-like files at the root of the project.

We could revisit this issue when the project grows. Thanks for the proposal.

**Pull request closed without merging**
